//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netz.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("netz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // This is a template. Do not remove //# strings
        ///using System;
        ///using System.IO;
        ///using System.Resources;
        ///using System.Reflection;
        ///using System.Collections.Specialized;
        ///
        /////#ZIPHEAD
        ///
        ///// for log only in winexe mode
        ///using System.Windows.Forms;
        ///
        /////#AI
        /////#UAI
        ///
        ///namespace netz
        ///{
        ///
        ///    //#NTSERVICE
        ///
        ///
        ///    public class NetzStarter//#VER
        ///    {
        ///        #region constants
        ///
        ///        private static readonly string Name = &quot;Name&quot;;
        ///        private static readonly string Culture = &quot;Culture&quot;;
        ///        inte [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     [System.ComponentModel.RunInstaller(true)]
        ///    public class ProjectInstaller : System.Configuration.Install.Installer
        ///    {
        ///        public static readonly string SERVICENAME = //#NTS_NAME;
        ///
        ///        private System.ServiceProcess.ServiceProcessInstaller serviceProcessInstaller;
        ///        private System.ServiceProcess.ServiceInstaller serviceInstaller;
        ///
        ///        public ProjectInstaller()
        ///        {
        ///            serviceInstaller = new System.ServiceProcess.ServiceInstaller();
        ///            serviceProces [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string serviceData {
            get {
                return ResourceManager.GetString("serviceData", resourceCulture);
            }
        }
    }
}
